name: Build and Release Game

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Pygame and PyInstaller
        run: |
          pip install pygame pyinstaller
      - name: Build Executable
        run: |
          pyinstaller --onefile --name TheSnake --distpath ./bin src/main.py
      - name: Archive Executable
        run: |
          cd bin
          Compress-Archive -Path TheSnake.exe -DestinationPath ../TheSnake.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: game
          path: TheSnake.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: game
          path: bin
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: 'New release of the game.'
          assets: ./bin/TheSnake.zip
