name: Build and Release Game

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~\.cache\pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Executable
        run: pyinstaller --noconfirm \
            --log-level=WARN \
            --path . \
            --name TheSnake \
            --icon ./assets/TheSnake.ico \
            --distpath ./bin \
            --workpath ./build \
            --noconsole \
            --onefile \
            src/main.py
